=== BPetra10/Olympics_xquery/7/PlaceYearEvent.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <!-- custom type for the year to restrict the range between 1896 and 2016 -->
    <xs:simpleType name="OlympicYear">
        <xs:restriction base="xs:gYear">
            <xs:minInclusive value="1896"/>
            <xs:maxInclusive value="2016"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:element name="olympic">
        <xs:complexType>
            <xs:sequence>
                
                <xs:element name="events">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="event" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="location" type="xs:string"/>
                                        <xs:element name="year" type="OlympicYear"/>       
                                        <xs:element name="eventType" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="locations">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="location" maxOccurs="unbounded" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== BPetra10/Olympics_xquery/7/PlaceYearEvent.xml
<?xml version="1.0" encoding="UTF-8"?>
<olympic xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="PlaceYearEvent.xsd">
    <events>
        <event>
            <location>Amsterdam</location>
            <year>1928</year>
            <eventType>10000M Men</eventType>
        </event>
        <event>
            <location>Amsterdam</location>
            <year>1928</year>
            <eventType>100M Men</eventType>
        </event>
        <event>
            <location>Amsterdam</location>
            <year>1928</year>
            <eventType>100M Women</eventType>
        </event>
        <event>
            <location>Amsterdam</location>
            <year>1928</year>
            <eventType>110M Hurdles Men</eventType>
        </event>
        <event>
            <location>Amsterdam</location>
            <year>1928</year>
            <eventType>1500M Men</eventType>
        </event>
        <event>
            <location>Amsterdam</location>
            <year>1928</year>
            <eventType>200M Men</eventType>
        </event>
        <event>
            <location>Amsterdam</location>
            <year>1928</year>
            <eventType>3000M Steeplechase Men</eventType>
        </event>
        <event>
            <location>Amsterdam</location>
            <year>1928</year>
            <eventType>400M Hurdles Men</eventType>
        </event>
        <event>
            <location>Amsterdam</location>
            <year>1928</year>
            <eventType>400M Men</eventType>
        </event>
        <event>
            <location>Amsterdam</location>
            <year>1928</year>
            <eventType>4X100M Relay Men</eventType>
        </event>
        <event>
            <location>Amsterdam</location>
            <year>1928</year>
            <eventType>4X100M Relay Women</eventType>
        </event>
        <event>
            <location>Amsterdam</location>
            <year>1928</year>
            <eventType>4X400M Relay Men</eventType>
        </event>
        <event>
            <location>Amsterdam</location>
            <year>1928</year>
            <eventType>5000M Men</eventType>
        </event>
        <event>
            <location>Amsterdam</location>
            <year>1928</year>
            <eventType>800M Men</eventType>
        </event>
        <event>
            <location>Amsterdam</location>
            <year>1928</year>
            <eventType>800M Women</eventType>
        </event>
        <event>
            <location>Amsterdam</location>
            <year>1928</year>
            <eventType>Decathlon Men</eventType>
        </event>
        <event>
            <location>Amsterdam</location>
            <year>1928</year>
            <eventType>Discus Throw Women</eventType>
        </event>
        <event>
            <location>Amsterdam</location>
            <year>1928</year>
            <eventType>Long Jump Men</eventType>
        </event>
        <event>
            <location>Amsterdam</location>
            <year>1928</year>
            <eventType>Marathon Men</eventType>
        </event>
        <event>
            <location>Antwerp</location>
            <year>1920</year>
            <eventType>10000M Men</eventType>
        </event>
        <event>
            <location>Antwerp</location>
            <year>1920</year>
            <eventType>100M Men</eventType>
        </event>
        <event>
            <location>Antwerp</location>
            <year>1920</year>
            <eventType>110M Hurdles Men</eventType>
        </event>
        <event>
            <location>Antwerp</location>
            <year>1920</year>
            <eventType>1500M Men</eventType>
        </event>
        <event>
            <location>Antwerp</location>
            <year>1920</year>
            <eventType>200M Men</eventType>
        </event>
        <event>
            <location>Antwerp</location>
            <year>1920</year>
            <eventType>3000M Steeplechase Men</eventType>
        </event>
        <event>
            <location>Antwerp</location>
            <year>1920</year>
            <eventType>400M Hurdles Men</eventType>
        </event>
        <event>
            <location>Antwerp</location>
            <year>1920</year>
            <eventType>400M Men</eventType>
        </event>
        <event>
            <location>Antwerp</location>
            <year>1920</year>
            <eventType>4X100M Relay Men</eventType>
        </event>
        <event>
            <location>Antwerp</location>
            <year>1920</year>
            <eventType>4X400M Relay Men</eventType>
        </event>
        <event>
            <location>Antwerp</location>
            <year>1920</year>
            <eventType>5000M Men</eventType>
        </event>
        <event>
            <location>Antwerp</location>
            <year>1920</year>
            <eventType>800M Men</eventType>
        </event>
        <event>
            <location>Antwerp</location>
            <year>1920</year>
            <eventType>Decathlon Men</eventType>
        </event>
        <event>
            <location>Antwerp</location>
            <year>1920</year>
            <eventType>Marathon Men</eventType>
        </event>
        <event>
            <location>Athens</location>
            <year>1896</year>
            <eventType>100M Men</eventType>
        </event>
        <event>
            <location>Athens</location>
            <year>1896</year>
            <eventType>110M Hurdles Men</eventType>
        </event>
        <event>
            <location>Athens</location>
            <year>1896</year>
            <eventType>1500M Men</eventType>
        </event>
        <event>
            <location>Athens</location>
            <year>1896</year>
            <eventType>400M Men</eventType>
        </event>
        <event>
            <location>Athens</location>
            <year>1896</year>
            <eventType>800M Men</eventType>
        </event>
        <event>
            <location>Athens</location>
            <year>1896</year>
            <eventType>Discus Throw Men</eventType>
        </event>
        <event>
            <location>Athens</location>
            <year>1896</year>
            <eventType>High Jump Men</eventType>
        </event>
        <event>
            <location>Athens</location>
            <year>1896</year>
            <eventType>Long Jump Men</eventType>
        </event>
        <event>
            <location>Athens</location>
            <year>1896</year>
            <eventType>Marathon Men</eventType>
        </event>
        <event>
            <location>Athens</location>
            <year>1896</year>
            <eventType>Pole Vault Men</eventType>
        </event>
        <event>
            <location>Athens</location>
            <year>1896</year>
            <eventType>Shot Put Men</eventType>
        </event>
        <event>
            <location>Athens</location>
            <year>1896</year>
            <eventType>Triple Jump Men</eventType>
        </event>
        <event>
            <location>Athens</location>
            <year>2004</year>
            <eventType>10000M Men</eventType>
        </event>
        <event>
            <location>Athens</location>
            <year>2004</year>
            <eventType>10000M Women</eventType>
        </event>
        <event>
            <location>Athens</location>
            <year>2004</year>
            <eventType>100M Hurdles Women</eventType>
        </event>
        <event>
            <location>Athens</location>
            <year>2004</year>
            <eventType>100M Men</eventType>
        </event>
        <event>
            <location>Athens</location>
            <year>2004</year>
            <eventType>100M Women</eventType>
        </event>
        <event>
            <location>Athens</location>
            <year>2004</year>
            <eventType>110M Hurdles Men</eventType>
        </event>
        <event>
            <location>Athens</location>
            <year>2004</year>
            <eventType>1500M Men</eventType>
        </event>
        <event>
            <location>Athens</location>
            <year>2004</year>
            <eventType>1500M Women</eventType>
        </event>
        <event>
            <location>Athens</location>
            <year>2004</year>
            <eventType>200M Men</eventType>
        </event>
        <event>
            <location>Athens</location>
            <year>2004</year>
            <eventType>200M Women</eventType>
        </event>
        <event>
            <location>Athens</location>
            <year>2004</year>
            <eventType>20Km Race Walk Men</eventType>
        </event>
        <event>
            <location>Athens</location>
            <year>2004</year>
            <eventType>20Km Race Walk Women</eventType>
        </event>
        <event>
            <location>Athens</location>
            <year>2004</year>
            <eventType>3000M Steeplechase Men</eventType>
        </event>
        <event>
            <location>Athens</location>
            <year>2004</year>
            <eventType>400M Hurdles Men</eventType>
        </event>
        <event>
            <location>Athens</location>
            <year>2004</year>
            <eventType>400M Hurdles Women</eventType>
        </event>
        <event>
            <location>Athens</location>
            <year>2004</year>
            <eventType>400M Men</eventType>
        </event>
        <event>
            <location>Athens</location>
            <year>2004</year>
            <eventType>400M Women</eventType>
        </event>
        <event>
            <location>Athens</location>
            <year>2004</year>
            <eventType>4X100M Relay Men</eventType>
        </event>
        <event>
            <location>Athens</location>
            <year>2004</year>
            <eventType>4X100M Relay Women</eventType>
        </event>
        <event>
