=== BPetra10/Olympics_xquery/3/FirstLast.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="runs">
        <xs:complexType>
            <xs:sequence>
                
                <xs:element name="fastestRunner">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="res" type="xs:string"/>
                            <xs:element name="resInSec" type="xs:decimal"/>
                        </xs:sequence>
                        <xs:attribute name="location" type="xs:string" use="required"/>
                        <xs:attribute name="year" type="xs:gYear" use="required"/>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="slowestRunner">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="res" type="xs:string"/>
                            <xs:element name="resInSec" type="xs:decimal"/>
                        </xs:sequence>
                        <xs:attribute name="location" type="xs:string" use="required"/>
                        <xs:attribute name="year" type="xs:gYear" use="required"/>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="differenceInTime">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="differenceInSeconds" type="differenceInSeconds"/>
                            <xs:element name="differenceInMin" type="differenceInMin"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:simpleType name="differenceInSeconds">
            <xs:restriction base="xs:decimal">
                <xs:fractionDigits value="3"/>
            </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="differenceInMin">
            <xs:restriction base="xs:string">
                <!-- accepts: from x:x.x to xx:xx:xxx-->
                <xs:pattern value="\d{1,2}:\d{1,2}\.\d{1,3}"/>
            </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== BPetra10/Olympics_xquery/3/FirstLast.xml
<?xml version="1.0" encoding="UTF-8"?>
<runs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="FirstLast.xsd">
    <fastestRunner location="Rio" year="2016">
        <name>Mohamed FARAH</name>
        <res>25:05.17</res>
        <resInSec>1505.017</resInSec>
    </fastestRunner>
    <slowestRunner location="Antwerp" year="1920">
        <name>Paavo NURMI</name>
        <res>31:45.8</res>
        <resInSec>1905.008</resInSec>
    </slowestRunner>
    <differenceInTime>
        <differenceInSeconds>399.991</differenceInSeconds>
        <differenceInMin>6:39.991</differenceInMin>
    </differenceInTime>
</runs>
